site_name: Data Science
site_url: https://datasci.danforthcenter.org
site_description: Documentation for the Data Science Facility at the Donald Danforth Plant Science Center
site_author: Donald Danforth Plant Science Center
repo_url: https://github.com/datascience
copyright: 'Copyright &copy; 2024 Donald Danforth Plant Science Center'
theme: readthedocs

nav:
  - Home: index.md
  - "Getting started": gettingstarted.md
  - "Usage policies": policies.md
  - "Conda":
    - "Why use conda?": conda_why.md
    - "Setup conda": conda.md
    - "Conda environments": conda_envs.md

markdown_extensions:
  - toc:
      permalink: True
  - sane_lists
  - admonition
